### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by jrue00** [decohn/nfl-spread-pools#1]
Will you be updating this weekly for Thursday Night games as well? Would love to see how it stacks up throughout the season. I am doing a school project for NFL variables impact on outcome

**Comment by decohn** [comment]
Hi jrue00, thanks for your interest in the project.

I'll push TNF-only predictions up every Thursday at some point in the afternoon/evening. I typically like to wait until just 15-30 minutes before kickoff to capture as much late movement in the point spread as possible, but some days (like today) my schedule will necessitate me putting the predictions up sooner.

**Comment by jrue00** [comment]
Thanks so much.
