### ISSUE TITLE
Error with arguments

### ISSUE THREAD

**Issue by omar319** [decohn/nfl-spread-pools#2]
Hello,

Not sure where to add the arguments, I'm rusty with R, I am running your make_weekly_prediction script and receive (if I hard code it then it runs but then I get an error on `predictions <- map2` 

```
Error in `map2()`:
ℹ In index: 2.
ℹ With name: SVM3.
Caused by error in `UseMethod()`:
! no applicable method for 'predict' applied to an object of class "train"
Run `rlang::last_trace()` to see where the error occurred.
```

```
Make weekly NFL predictions using previously trained models.

positional arguments:
  2023        The season to make predictions for.
  11          The week to make predictions for.

flags:
  -h, --help  show this help message and exit

optional arguments:
  -x, --opts  RDS file containing argument values

Error in parse_args(p) : 
  Missing required arguments: expecting 2 values but got 0 values: ().
```

**Comment by decohn** [comment]
Hi,

It's probably easiest to run make_weekly_predictions.R from the command line as is, **without** hard-coding anything, i.e. by navigating to your local version of the `nfl-spread-pools` folder and then running `./make_weekly_predictions.R 2023 11`.

That said, hard-coding the arguments into the script (i.e. replacing the assignments for `season` and `week` with `season <- "2023"` and `week <- 11`) and then sourcing the script in R should also work. I'm not entirely sure what would be causing the `predict` error that you saw, assuming that the repository was fully cloned.

Please let me know if my command line suggestion works for you - if not, I'll look further into that `predict` error that you encountered.

**Comment by omar319** [comment]
I cloned and even just did a clean pull and all up to date and receive this

```
✔ Reading from 2023 NFL Pick Tracker.
✔ Range Predictor.
Error in `map2()`:
ℹ In index: 2.
ℹ With name: SVM3.
Caused by error in `UseMethod()`:
! no applicable method for 'predict' applied to an object of class "train"
Backtrace:
     ▆
  1. ├─... %>% select(Road, Home, everything())
  2. ├─dplyr::select(., Road, Home, everything())
  3. ├─dplyr::mutate(., Road = weekly_games$Road, Home = weekly_games$Home)
  4. ├─dplyr::bind_cols(.)
  5. │ └─rlang::list2(...)
  6. ├─purrr::map2(...)
  7. │ └─purrr:::map2_("list", .x, .y, .f, ..., .progress = .progress)
  8. │   ├─purrr:::with_indexed_errors(...)
  9. │   │ └─base::withCallingHandlers(...)
 10. │   ├─purrr:::call_with_cleanup(...)
 11. │   └─global .f(.x[[i]], .y[[i]], ...)
 12. │     └─tibble::tibble(...)
 13. │       └─tibble:::tibble_quos(xs, .rows, .name_repair)
 14. │         └─rlang::eval_tidy(xs[[j]], mask)
 15. ├─stats::predict(.x, newdata = weekly_games)
 16. └─base::.handleSimpleError(...)
 17.   └─purrr (local) h(simpleError(msg, call))
 18.     └─cli::cli_abort(...)
 19.       └─rlang::abort(...)
Execution halted
```

**Comment by decohn** [comment]
Hmm. I'm having some trouble replicating that error on my end in a fresh R session, but I think it might have to do with the generic `predict` function not invoking the `predict` function from the packages used to train the models.

Does adding `library(caret)` to the `suppressPackageStartupMessages` block make any difference for you? If not, what about adding both `library(ranger)` and `library(LiblineaR)`?

**Comment by omar319** [comment]
looks like that worked but now that I added all 3 I get the following

```
$ RScript make_weekly_predictions.R 2023 12
✔ Reading from 2023 NFL Pick Tracker.
✔ Range Predictor.
Error: sample_fraction too small, no observations sampled. Ranger will EXIT now.
Error in `map2()`:
ℹ In index: 3.
ℹ With name: Maxstat RF.
Caused by error in `predict.ranger.forest()`:
! User interrupt or internal error.
Backtrace:
     ▆
  1. ├─... %>% select(Road, Home, everything())
  2. ├─dplyr::select(., Road, Home, everything())
  3. ├─dplyr::mutate(., Road = weekly_games$Road, Home = weekly_games$Home)
  4. ├─dplyr::bind_cols(.)
  5. │ └─rlang::list2(...)
  6. ├─purrr::map2(...)
  7. │ └─purrr:::map2_("list", .x, .y, .f, ..., .progress = .progress)
  8. │   ├─purrr:::with_indexed_errors(...)
  9. │   │ └─base::withCallingHandlers(...)
 10. │   ├─purrr:::call_with_cleanup(...)
 11. │   └─global .f(.x[[i]], .y[[i]], ...)
 12. │     └─tibble::tibble(...)
 13. │       └─tibble:::tibble_quos(xs, .rows, .name_repair)
 14. │         └─rlang::eval_tidy(xs[[j]], mask)
 15. ├─stats::predict(.x, newdata = weekly_games)
 16. ├─caret::predict.train(.x, newdata = weekly_games)
 17. │ └─caret::predictionFunction(...)
 18. │   └─method$predict(modelFit = modelFit, newdata = newdata, submodels = param)
 19. │     ├─stats::predict(modelFit, newdata)
 20. │     └─ranger:::predict.ranger(modelFit, newdata)
 21. │       ├─stats::predict(...)
 22. │       └─ranger:::predict.ranger.forest(...)
 23. │         └─base::stop("User interrupt or internal error.")
 24. └─base::.handleSimpleError(...)
 25.   └─purrr (local) h(simpleError(msg, call))
 26.     └─cli::cli_abort(...)
 27.       └─rlang::abort(...)
Execution halted
```

**Comment by decohn** [comment]
The cause of that error was just that there hadn't been any data for Week 12 entered into the source spreadsheet (https://docs.google.com/spreadsheets/d/1dVnTsDZvxPkLAsYW6SPb1tOTNHe2bxtRAAwpPIAYwj0/edit?usp=sharing) at that time. Please try running `make_weekly_predictions.R 2023 12` again, as it should work now.

I typically update that spreadsheet the night before games, Pacific Time (i.e. on Wednesdays and Saturdays, usually).

**Comment by omar319** [comment]
that seemed to work, is it only supposed to do games that have already played only or the rest as well? I only see these::

```
Predictions stored at 2023/weekly-predictions/week-12.csv:
Road,Home,DAVE + Spread LM,SVM3,Maxstat RF
GB,Det,7.6,7.47,9.17
Was,Dal,12.47,12.36,18.18
SF,Sea,-7.15,-7.05,-6.64
Mia,NYJ,-8.68,-8.73,-7.65
```

**Comment by decohn** [comment]
The `make_weekly_predictions.R` script will make predictions for all games in the current week that have been entered into the source spreadsheet (linked in my comment above).

Under normal circumstances, I enter games into that spreadsheet the night before they are played. So for example, predictions for tomorrow's Seattle-Dallas game will be available at some point tonight. Predictions for games played on Sundays will be available on Saturday nights. Data in the spreadsheet may also be updated on gameday (e.g. if the line moves), which will in turn impact the predictions.
